spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/curso
    username: curso
    password: curso
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: public
    baseline-on-migrate: true
    schemas: public

stripe:
    api:
      key: key
